### ISSUE TITLE
wrong number of arguments (13 for 5..12) after calling rec_new (cloudflare_dns_record provider)

### ISSUE THREAD

**Issue by rafaelfelix** [wk8/cookbook-cloudflare#14]
Steps to reproduce:
- Install cookbook-cloudflare, latest version from git (as the current chef supermarket is broken, as stated in https://github.com/wk8/cookbook-cloudflare/issues/9)
- Define a cloudflare_dns_record resource as follows:

```
  cloudflare_dns_record "create-record" do
    name    "test"
    zone    "yourcloudflarehostedzone.com"
    type    "A"
    content "200.200.200.200"
    action  :create
  end
```
- Run this and you should get:

```
[2015-11-06T17:01:44+00:00] INFO: Creating DNS record test.yourcloudflarehostedzone.com^[[0m
================================================================================^[[0m
^[[31mError executing action `create` on resource 'cloudflare_dns_record[test]'^[[0m
================================================================================^[[0m

^[[0m
ArgumentError^[[0m
-------------^[[0m
wrong number of arguments (13 for 5..12)^[[0m

^[[0m
Cookbook Trace:^[[0m
---------------^[[0m
/var/lib/aws/opsworks/cache.stage2/cookbooks/cloudflare/libraries/cloudflare.rb:97:in `rec_new'
/var/lib/aws/opsworks/cache.stage2/cookbooks/cloudflare/resources/dns_record.rb:64:in `create'
/var/lib/aws/opsworks/cache.stage2/cookbooks/cloudflare/providers/dns_record.rb:19:in `block in class_from_file'^[[0m

^[[0m
Resource Declaration:^[[0m
---------------------^[[0m
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/gn_cloudflare/recipes/default.rb

 24:   cloudflare_dns_record "create-record" do
 25:     name    "test"
 26:     zone    "yourcloudflarehostedzone.com"
 27:     type    "A"
 28:     content "200.200.200.200"
 29:     action  :create
 30:   end
 31: end
^[[0m
^[[0m
Compiled Resource:^[[0m
------------------^[[0m
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/gn_cloudflare/recipes/default.rb:24:in `block in from_file'

cloudflare_dns_record("test") do
  action :create
  updated true
  updated_by_last_action true
  retries 0
  retry_delay 2
  cookbook_name "mycookbook"
  recipe_name "default"
  zone "yourcloudflarehostedzone.com"
  type "A"
  content "200.200.200.200"
  record_name "test"
  ttl 1
  service_mode "0"
end
^[[0m
```

**Comment by josacar** [comment]
Looks like code in master of the gem isn't version 2.0.3, so this doesn't work. Gem author should release a new version and then fix it in this cookbook.
